[16기 이혜성] Feature/bookview 생성 및 뷰 작성 완료
wecode-bootcamp-korea/16-2nd-milliem-sasur-backend pull request #4
Opened 2021-02-02 09:50 UTC by hyeseong-dev

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 로그인 버튼 활성화 기능 구현(예시)
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- id '@' 포함, pw 5 글자 이상 입력 시 버튼 활성화(예시)

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 함수 로직이 너무 긴 것 같습니다. 좀 더 효율적인 방법이 없을지 궁금합니다.(예시) 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.
- [ ] Git rebase와 squash를 했고 커밋 수가 하나 인것을 확인 했습니다.

2021-02-02 10:52 UTC, hyeseong-dev commented
- 16개 merge conflict 해결
- models.py 수정
- book app API 작성
- 유닛테스트 미작성(TODO)

2021-02-02 15:11 UTC, ulfrid requested changes
확인해주세요~!

2021-02-02 15:11 UTC, devops-andrew commented on book/views.py
> +
이런 빈줄은 주지 않는게 좋을것 같아요~!

2021-02-02 15:11 UTC, devops-andrew commented on book/views.py
> +                    )
```suggestion
          slider = [ {
                            'id'           :idx,
                            'bookTitle'    :book.title,
                            'bookCoverImg' :book.image_url,
                            'bookAuthor'   :book.author.name,
                        } for idx,book in enumerate(Book.objects.prefetch_related("author", "publisher", ).filter(category__id=category_id).order_by('?')[OFFSET:LIMIT],1)]
```
리스트 컴프리헨션을 사용해주세요.

2021-02-02 15:11 UTC, devops-andrew commented on book/views.py
> +
이런식으로 한번에 하길 바라지 않았지만, 지금 시점에서 이걸 갈아 엎는건 어려울 것 같으니, 일단 리스트 컴프리헨션 적용해서 코드조금 더 간결하게 바꿔주시기 바랍니다~!

2021-02-02 16:39 UTC, hyeseong-dev commented on book/views.py
> +
네! 확인해서 빈줄 없애도록 하겠습니다

2021-02-02 16:41 UTC, hyeseong-dev commented on book/views.py
> +                    )
간단한 리스트 컴프리헨션은 하겠는데. 무언가 길어진다는 생각에 하지 못했는데. 깔끔하게 보여주셔서 감사합니다. 참고해서 적용하도록 할게요.✌🤳🐱‍🏍

2021-02-02 16:42 UTC, hyeseong-dev commented on book/views.py
> +
네에!😁

2021-02-03 07:06 UTC, soheon-lee commented on book/urls.py
> +    path('/<int:category_id>', views.BookListView.as_view()),
책 리스트를 표출하는 API의 url `books`뒤에 `category_id`가 슬래시 뒤에 오는 것은 RESTful 규칙에 알맞지 않습니다
필터링을 하려면 category_id를 어떻게 활용하면 좋을까요

2021-02-03 07:07 UTC, soheon-lee commented on users/models.py
> +    # library           = models.OneToOneField('library.Library', on_delete=models.CASCADE, related_name='users')
더이상 사용되지 않는 field라면 주석 처리보다는 삭제해주세요 :)

2021-02-03 07:24 UTC, hyeseong-dev commented on book/urls.py
> +    path('/<int:category_id>', views.BookListView.as_view()),
소헌님 아래와 같이 하면 RESTful 규칙에 맞을지 모르겠네요. 

```python
from django.urls import path
from book        import views

urlpatterns = [
    path('/category/<int:category_id>',    views.BookListView.as_view()),
    path('/detail/<int:book_id>',               views.BookDetailView.as_view()),
    path('/<int:book_id>/review',             views.ReviewView.as_view()),
    path('/reviewlike',                              views.ReviewLikeView.as_view()),
    path('/search',                                   views.SearchView.as_view()),
]
```

2021-02-03 07:25 UTC, hyeseong-dev commented on users/models.py
> +    # library           = models.OneToOneField('library.Library', on_delete=models.CASCADE, related_name='users')
추가 구현에 쓸것같아서 주석으로 잠궈버리긴했는데. 삭제할게유 ㅠ.ㅠ

2021-02-03 07:31 UTC, hyeseong-dev commented
===
21.02.03. 16:30
[소헌님 요청에 대한 코드 수정 완료]
book앱 urls.py 및 models.py 수정
- urls.py       : restful규칙에 맞춰 재작성
- models.py : 빈주석 삭제 (추가 구현시 사용에 대한 연장선으로 주석 사용했었음) 


===
21.02.03. 02:14
[지훈님 코드 수정 요청에 대한 코드 수정 완료]
book 리스트 API 수정요청 완료 
    - view 수정
      + 기존 15번째 빈줄 삭제 및 빈 여백줄 모두 제거
      + 19~33lines (14줄 -> 6줄로 코드 축약)
      + 전체 약 106줄에서 -> 61줄내외로 압축
    -(TODO) unittest 진행예정(일시, 21.02.03. 09:00~)
    -(TODO) 프런트와 상시 통신을 위한 테스트 서버 구축(일시, 21.02.03 09:00~) AWS(EC2, RDS
    -(TODOO BookDetailView 작성 예정(일시, 21.02.03 09:00~19:00)
    -(TODO) BookDetailView Unittest 작성예정(상기 일시동일, 시간: 09:00 ~ 21:00)
    -(TODOO Docker Container Deployment in EC2 Server(21.02.03 ~ 21.02.04 발표전)

2021-02-03 07:38 UTC, soheon-lee commented on book/views.py
> +
book_id=500000 이렇게 넣으면 어떻게 되나요?
Review DoesNotExist 에러는 언제 나나요?

2021-02-03 07:55 UTC, hyeseong-dev commented
21.02.03 16:47
    [소헌님 "PR요청" 수정 요청에 대학 ReviewView 재작성]
    - 원인: 모델 클래스 이름 미 변경에 따른 `Model.DoesNotExist`기능을 하지 못했음
    - 해결방법 : 기존 `Review`->`Book`으로 변경

2021-02-03 07:57 UTC, hyeseong-dev commented on book/views.py
> +
빛소헌 덕에 오늘도 오류 잡아냅니다 ㅠ.ㅠ 

아래와 같이 `50000`만이라는 책번호를 넣으면 잡아내도록 수정하였습니다.

![image](https://user-images.githubusercontent.com/57933835/106715740-d573ac80-6640-11eb-9eb7-08576d81fe0e.png)

2021-02-03 08:55 UTC, ulfrid requested changes
유닛 테스트 하고 계신가요?

2021-02-03 08:55 UTC, ulfrid commented on book/views.py
> +
빈 줄 제거요~

2021-02-03 10:32 UTC, hyeseong-dev commented on book/views.py
> +
바로 드릴수 있도록 할게요. ㅠ.ㅠ

2021-02-04 06:00 UTC, hyeseong-dev commented on book/views.py
> +
아래와 같이 완료하였습니다. 
![image](https://user-images.githubusercontent.com/57933835/106851498-b38a3080-66f9-11eb-8894-27fb1146a06e.png)

2021-02-04 06:08 UTC, soheon-lee commented on book/tests.py
> +        book     = Book.objects.get(id=1)
이 `book` 변수는 언제 사용하나요?

2021-02-04 06:08 UTC, soheon-lee commented on book/tests.py
> +                                                                }],
```suggestion
        self.assertEqual(response.json(), {
            'bookData': {
                "slider"            : 
                                                                    [{
                                                                    'id'           : 1,
                                                                    'category.id'  : 1,
                                                                    'category.name': '일반소설',
                                                                    'book_id'      : 1,
                                                                    'bookTitle'    :'title',
                                                                    'bookCoverImg' :'image_url',
                                                                    'bookAuthor'   : 'name',
                                                                }],
```

코드 앞 부분에 여백이 너무 길어서 가독성을 해칠 수 있습니다 :)
앞에 공백 줄여주세요~

2021-02-04 06:08 UTC, soheon-lee commented on book/urls.py
> +    path('/search/<str:keyword>',          views.SearchView.as_view()),
```suggestion
    path('', views.BookListView.as_view()),
    path('/detail/<int:book_id>', views.BookDetailView.as_view()),
    path('/<int:book_id>/review', views.ReviewView.as_view()),
    path('/reviewlike', views.ReviewLikeView.as_view()),
    path('/search/<str:keyword>', views.SearchView.as_view()),
```

2021-02-04 06:08 UTC, soheon-lee commented on book/views.py
> +
```suggestion
            slider = [ {
                'id'           :idx,
                'category.id'  :book.category.id,
                            'category.name':book.category.name,
                            'book_id'      :book.id,
                            'bookTitle'    :book.title,
                            'bookCoverImg' :book.image_url,
                            'bookAuthor'   :book.author.name,
                        } for idx,book in enumerate(Book.objects.prefetch_related("author", "publisher")\
                        .filter(category__id=category_id).order_by('?')[OFFSET:LIMIT],1) ]

```

2021-02-04 06:11 UTC, hyeseong-dev commented on book/urls.py
> +    path('/search/<str:keyword>',          views.SearchView.as_view()),
홖아악~ 땅겨버릴게용~

2021-02-04 06:11 UTC, hyeseong-dev commented on book/tests.py
> +                                                                }],
알겠숨돠~~~~

2021-02-04 06:12 UTC, hyeseong-dev commented on book/tests.py
> +        book     = Book.objects.get(id=1)
더 이상 사용하지 않아요~ 확인해주셔서 감사합니돠~

2021-02-04 06:57 UTC, hyeseong-dev commented on book/views.py
> +
홖아악~ 땅겨버릴게용~~~~~~~~~~~~~~~~~~~~~~~~~

2021-02-04 06:58 UTC, hyeseong-dev commented
BookDetailView Unit Test 하기와 같이 완료했습니돠~
![image](https://user-images.githubusercontent.com/57933835/106856485-df111900-6701-11eb-85bf-1ef71047eb59.png)

2021-02-04 07:58 UTC, soheon-lee commented on book/tests.py
> +class BookDetailest(TestCase):
```suggestion
class BookDetailTest(TestCase):
```

2021-02-04 07:58 UTC, soheon-lee commented on book/tests.py
> +
불필요한 공백인 것 같습니다 :)

2021-02-04 07:58 UTC, soheon-lee commented on book/urls.py
> +    path('/detail/<int:book_id>', views.BookDetailView.as_view()),
```suggestion
    path('/<int:book_id>', views.BookDetailView.as_view()),
```
RESTful API 규칙에서 특정 리소스 뒤에 `id`가 오면 그 리소스의 상세 정보임을 뜻합니다 그래서 `detail`이라는 단어는 주로 사용하지는 않습니다. 꼭 수정하시지는 않으셔도 됩니다. 일반적인 경우가 아니라는 것을 전달드립니다 :)

2021-02-04 07:58 UTC, soheon-lee commented
@hyeseong-dev 혜성님 테스트케이스 좋습니다!! 이대로 쭉 다른 엔드포인트도 작성해주시면 되겠습니다 !! 화이팅

2021-02-04 08:22 UTC, hyeseong-dev commented on book/tests.py
> +class BookDetailest(TestCase):
확인 고마워요!

2021-02-04 08:23 UTC, hyeseong-dev commented on book/tests.py
> +
공백 쫙쫙 당길게요

2021-02-04 08:25 UTC, hyeseong-dev commented on book/urls.py
> +    path('/detail/<int:book_id>', views.BookDetailView.as_view()),
빛소헌님 감사해유~
그렇다면 
`localhost:8000/book'   + `/1' 와 같이 조합하고 아래와 같이 간단하게 작성하는건가유?
(예. `localhost:8000/book/<int:book_id>`)

2021-02-04 08:30 UTC, soheon-lee commented on book/urls.py
> +    path('/detail/<int:book_id>', views.BookDetailView.as_view()),
@hyeseong-dev 네 맞습니담!

2021-02-04 08:31 UTC, soheon-lee commented
LGTM

2021-02-04 08:31 UTC, merged